###   Business Problem Statement

- How can companies optimize their marketing campaigns to improve conversion rates and maximize return on investment (ROI)?

- Companies invest significant budgets in marketing campaigns across different channels and campaign types. However, not all campaigns perform equally. The goal of this analysis is to identify which campaign strategies, channels, and target audiences generate the highest marketing performance.

In [1]:
import pandas as pd

In [2]:
df=pd.read_excel(r"C:\Users\DELL\Downloads\marketing_campaign_dataset.xlsx")

In [3]:
df.shape

(200005, 15)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200005 entries, 0 to 200004
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       200005 non-null  int64
 1   Company           200005 non-null  object
 2   Campaign_Type     200005 non-null  object
 3   Target_Audience   200005 non-null  object
 4   Duration          200005 non-null  object
 5   Channel_Used      200005 non-null  object
 6   Conversion_Rate   200005 non-null  float64
 7   Acquisition_Cost  200005 non-null  int64
 8   ROI               200005 non-null  float64
 9   Location          200005 non-null  object
 10  Date              200005 non-null  object
 11  Clicks            200005 non-null  int64
 12  Impressions       200005 non-null  int64
 13  Engagement_Score  200005 non-null  int64
 14  Customer_Segment  200005 non-null  object
dtypes: float64(2), int64(5), object(8)
memory usage: 22.9+ MB

In [5]:
df.head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Date,Clicks,Impressions,Engagement_Score,Customer_Segment
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,16174,6.29,Chicago,2021-01-01 00:00:00,506,1922,6,Health & Wellness
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,11566,5.61,New York,2021-02-01 00:00:00,116,7523,7,Fashionistas
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,10200,7.18,Los Angeles,2021-03-01 00:00:00,584,7698,1,Outdoor Adventurers
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,12724,5.55,Miami,2021-04-01 00:00:00,217,1820,7,Health & Wellness
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,16452,6.50,Los Angeles,2021-05-01 00:00:00,379,4201,3,Health & Wellness

In [6]:
df.duplicated().any()

np.False_

In [7]:
df[['Gender','Age_Group']] = df['Target_Audience'].str.split(' ', expand=True)
df.drop(columns=['Target_Audience'], inplace=True)

In [8]:
df['Duration'] = df['Duration'].str.replace(' days','').astype(int)

In [9]:
df['Date'] = pd.to_datetime(df['Date']).dt.strftime('%Y-%m-%d')

In [10]:
df['Total_Revenue'] = df['Acquisition_Cost'] * (df['ROI'] + 1)

In [11]:
df['CTR'] = (df['Clicks'] / df['Impressions']) * 100

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200005 entries, 0 to 200004
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       200005 non-null  int64
 1   Company           200005 non-null  object
 2   Campaign_Type     200005 non-null  object
 3   Duration          200005 non-null  int64
 4   Channel_Used      200005 non-null  object
 5   Conversion_Rate   200005 non-null  float64
 6   Acquisition_Cost  200005 non-null  int64
 7   ROI               200005 non-null  float64
 8   Location          200005 non-null  object
 9   Date              200005 non-null  object
 10  Clicks            200005 non-null  int64
 11  Impressions       200005 non-null  int64
 12  Engagement_Score  200005 non-null  int64
 13  Customer_Segment  200005 non-null  object
 14  Gender            200005 non-null  object
 15  Age_Group         200005 non-null  object
 16  Total_Revenue     200005 non-null  float64
 17  CTR               200005 non-null  float64
dtypes: float64(4), int64(6), object(8)
memory usage: 27.5+ MB

In [13]:
df.head(2)

,Campaign_ID,Company,Campaign_Type,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Date,Clicks,Impressions,Engagement_Score,Customer_Segment,Gender,Age_Group,Total_Revenue,CTR
0,1,Innovate Industries,Email,30,Google Ads,0.04,16174,6.29,Chicago,2021-01-01,506,1922,6,Health & Wellness,Men,18-24,117908.46,26.326743
1,2,NexGen Systems,Email,60,Google Ads,0.12,11566,5.61,New York,2021-02-01,116,7523,7,Fashionistas,Women,35-44,76451.26,1.541938

####   A/B Testing Problem Statement

## Business Problem

Companies invest in different marketing campaign types to acquire customers. However, it is unclear which campaign type generates better conversions.

## Objective

To determine whether Email marketing campaigns generate higher conversion rates than Social Media campaigns.

## A/B Test Design

- Group A (Control Group)
Email Campaigns

- Group B (Test Group)
Social Media Campaigns

Metric Used
Conversion Rate

## Hypothesis

- Null Hypothesis (H₀):
There is no significant difference in conversion rates between Email campaigns and Social Media campaigns.

- Alternative Hypothesis (H₁):
Email campaigns generate higher conversion rates than Social Media campaigns.

In [14]:
ab_data = df[df['Campaign_Type'].isin(['Email','Social Media'])]

In [15]:
email = ab_data[ab_data['Campaign_Type'] == 'Email']['Conversion_Rate']
social = ab_data[ab_data['Campaign_Type'] == 'Social Media']['Conversion_Rate']

In [16]:
from scipy.stats import ttest_ind

t_stat, p_value = ttest_ind(email, social, equal_var=False)

print("T-statistic:", t_stat)
print("P-value:", p_value)

T-statistic: -1.2004620269200839
P-value: 0.22996352038710474

alpha = 0.05

if p_value < alpha:
    print("Reject Null Hypothesis: Email campaigns generate significantly higher conversion rates than Social Media campaigns.")
else:
    print("Fail to Reject Null Hypothesis: No significant difference in conversion rates between Email and Social Media campaigns.")

####   A/B Test Result

The two-sample t-test results indicate that the p-value is greater than the significance level (α = 0.05). Therefore, we fail to reject the null hypothesis.

This suggests that there is no statistically significant difference in conversion rates between Email campaigns and Social Media campaigns.

 ## Business Interpretation

Although the average conversion rates of Email and Social Media campaigns may appear slightly different, the observed difference is not statistically significant and could be due to random variation in the data rather than a real effect.

##  Conclusion

- Based on the statistical test:

- Email campaigns do not significantly outperform Social Media campaigns.

- Social Media campaigns do not significantly outperform Email campaigns.

##  Business Recommendation

- Since both campaign types perform similarly in terms of conversion rate:

- Marketing budget can be allocated across both campaign types.

- Further analysis should focus on other factors, such as:

- marketing channel (Google Ads, Facebook, Instagram)

- target audience segments

- campaign duration

- These factors may provide more actionable insights for optimizing marketing performance.

##  A/B Testing Problem Statement

## Google Ads vs Facebook Campaigns


- Do Google Ads campaigns generate higher conversion rates than Facebook campaigns?

- Groups

- Group A: Google Ads campaigns
- Group B: Facebook campaigns

Metric

Conversion_Rate

##  Hypothesis

- Null Hypothesis (H₀):
There is no significant difference in conversion rates between Google Ads and Facebook campaigns.

- Alternative Hypothesis (H₁):
Google Ads campaigns generate higher conversion rates than Facebook campaigns.

In [17]:
ab_data = df[df['Channel_Used'].isin(['Google Ads','Facebook'])]

In [18]:
google_ads = ab_data[ab_data['Channel_Used'] == 'Google Ads']['Conversion_Rate']
facebook = ab_data[ab_data['Channel_Used'] == 'Facebook']['Conversion_Rate']

In [19]:
from scipy.stats import ttest_ind

t_stat, p_value = ttest_ind(google_ads, facebook, equal_var=False)

print("T-statistic:", t_stat)
print("P-value:", p_value)

T-statistic: 0.6043892360991725
P-value: 0.5455869601181698

In [20]:
alpha = 0.05

if p_value < alpha:
    print("Reject Null Hypothesis: Google Ads campaigns generate significantly higher conversion rates than Facebook campaigns.")
else:
    print("Fail to Reject Null Hypothesis: No significant difference in conversion rates between Google Ads and Facebook campaigns.")

Fail to Reject Null Hypothesis: No significant difference in conversion rates between Google Ads and Facebook campaigns.

####  A/B Test Result

The two-sample t-test produced a p-value greater than the significance level (α = 0.05). Therefore, we fail to reject the null hypothesis.

This indicates that there is no statistically significant difference in conversion rates between Google Ads and Facebook campaigns.

##  Business Interpretation

Although the average conversion rates for Google Ads and Facebook campaigns may differ slightly, the difference is not statistically significant and may be due to random variation in the data.

##  Conclusion

 Based on the statistical analysis:

- Google Ads campaigns do not significantly outperform Facebook campaigns.

- Facebook campaigns do not significantly outperform Google Ads campaigns.

##  Business Recommendation

Since both advertising platforms perform similarly in terms of conversion rate:

- Marketing budget can be allocated across both platforms.

- Further analysis should evaluate other factors such as:

-campaign type

- target audience

- customer segment

- campaign duration

These factors may provide more actionable insights for improving marketing performance.

In [21]:
from sqlalchemy import create_engine


user = 'root'
password = 'YOUR PASSWORD'
host = 'localhost'  
port = 3306
database = 'marketing_analysis'


engine = create_engine(f'mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}')

In [22]:
df.to_sql("marketing", engine, if_exists="replace", index=False)

print("Data uploaded successfully!")

Data uploaded successfully!